Updates designate spec Domain properties
Update the designate resource plugin spec to make
email property as required one and ttl property
as optional one.

designate CLI error:
 CLI : designate domain-create --name test.org
 Error: domain-create: error: argument --email is required

blueprint heat-designate-resource

Change-Id: Icaeef5afdcd7bacd2e54cb076bb5433e76f9d478